packages:
  - "packages/colony"
  - "packages/plugins/*"
  - "packages/storages/*"
  - "packages/observability/*"
  - "packages/security/*"
  - "packages/orchestration/*"
  - "packages/ai/*"
  - "packages/tools/*"
  - "packages/configs/*"

catalog:
  # TypeScript
  typescript: ^5.7.2

  # Build
  tsup: ^8.3.5

  # Testing
  vitest: ^4.0.16
  "@vitest/coverage-v8": ^4.0.16

  # Linting
  eslint: ^9.17.0
  "@eslint/js": ^9.17.0
  typescript-eslint: ^8.51.0
  globals: ^16.5.0

  # Types
  "@types/node": ^25.0.6
